### ISSUE TITLE
Object counting 

### ISSUE THREAD

**Issue by ZhexuanZhou** [gaoguangshuai/Counting-from-Sky-A-Large-scale-Dataset-for-Remote-Sensing-Object-Counting-and-A-Benchmark-Method#1]
In your paper, you present the counting results as 79.2, 551.6 and 823.6 etc. I am wondering how did you do the counting and obtain numbers like that?

**Comment by gaoguangshuai** [comment]
Thank you for your question. The count results are obtained from summing all the pixel values of the density maps, which can be found in many density estimation based crowd counting methods.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaoguangshuai/Counting-from-Sky-A-Large-scale-Dataset-for-Remote-Sensing-Object-Counting-and-A-Benchmark-Method"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 上午10:43
收件人:&nbsp;"gaoguangshuai/Counting-from-Sky-A-Large-scale-Dataset-for-Remote-Sensing-Object-Counting-and-A-Benchmark-Method"<Counting-from-Sky-A-Large-scale-Dataset-for-Remote-Sensing-Object-Counting-and-A-Benchmark-Method@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[gaoguangshuai/Counting-from-Sky-A-Large-scale-Dataset-for-Remote-Sensing-Object-Counting-and-A-Benchmark-Method] Object counting  (#1)





 
In your paper, you present the counting results as 79.2, 551.6 and 823.6 etc. I am wondering how did you do the counting and obtain numbers like that?
